name: Daily Commit

on:
  schedule:
    - cron: '23 7 * * *'  # Runs daily at 07:23 UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add dummy commit - 23f2002019@ds.study.iitm.ac.in
        run: |
          echo "Run at $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit - $(date)" || echo "Nothing to commit"
          git push

