name: Daily Commit

on:
  schedule:
    # Runs every day at 07:23 UTC (choose your preferred time)
    - cron: '23 7 * * *'
  workflow_dispatch:  # Optional: allows manual runs

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add dummy commit - 23f2002019@ds.study.iitm.ac.in
        run: |
          echo "Run at $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit - $(date)"
          git push

