name: Daily Commit

on:
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

permissions:
  contents: write  # ✅ this is the missing piece!

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add dummy commit - 23f2002019@ds.study.iitm.ac.in
        run: |
          echo "Run at $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit - $(date -u)" || echo "Nothing to commit"
          git push origin HEAD
